import type { CrudModuleConfig } from '@/lib/types';

export const menuItems = [
  { label: 'Painel Operacional', href: '/dashboard' },
  { label: 'Alertas', href: '/alertas' },
  { label: 'Painel Financeiro', href: '/financeiro' },
  { label: 'Veículos', href: '/veiculos' },
  { label: 'Motoristas', href: '/motoristas' },
  { label: 'Contratos', href: '/contratos' },
  { label: 'Vistorias', href: '/vistorias' },
  { label: 'Multas', href: '/multas' },
  { label: 'Sócios', href: '/socios' },
  { label: 'IAdrive', href: '/copiloto' },
];

const statusOptions = [
  { label: 'Ativo', value: 'active' },
  { label: 'Inativo', value: 'inactive' },
];

export const moduleConfigs = {
  veiculos: {
    slug: 'veiculos',
    title: 'Veículos',
    table: 'vehicles',
    orderBy: { column: 'created_at', ascending: false },
    fields: [
      { key: 'plate', label: 'Placa', type: 'text', required: true },
      { key: 'brand', label: 'Marca', type: 'text' },
      { key: 'model', label: 'Modelo', type: 'text' },
      { key: 'year', label: 'Ano', type: 'number' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Disponível', value: 'available' },
          { label: 'Alugado', value: 'rented' },
          { label: 'Vendido', value: 'sold' },
          { label: 'Manutenção', value: 'maintenance' },
        ],
      },
      {
        key: 'financing_status',
        label: 'Quitado ou financiado',
        type: 'select',
        options: [
          { label: 'Quitado', value: 'quitado' },
          { label: 'Financiado', value: 'financiado' },
        ],
      },
      { key: 'installments_total', label: 'Quantidade de parcelas', type: 'number' },
      { key: 'installment_value', label: 'Valor da parcela', type: 'number' },
      { key: 'financing_end_date', label: 'Data final do financiamento', type: 'date' },
      { key: 'notes', label: 'Observações', type: 'textarea' },
    ],
    listColumns: ['plate', 'brand', 'model', 'year', 'status', 'financing_status'],
  },

  motoristas: {
    slug: 'motoristas',
    title: 'Motoristas',
    table: 'drivers',
    orderBy: { column: 'created_at', ascending: false },
    fields: [
      { key: 'name', label: 'Nome', type: 'text', required: true },
      { key: 'cpf', label: 'CPF', type: 'text' },
      { key: 'phone', label: 'Telefone', type: 'text' },
      { key: 'cep', label: 'CEP', type: 'text' },
      { key: 'address', label: 'Endereço', type: 'text' },
      { key: 'latitude', label: 'Latitude', type: 'number' },
      { key: 'longitude', label: 'Longitude', type: 'number' },
      { key: 'cnh_due_date', label: 'Vencimento da CNH', type: 'date' },
      {
        key: 'payment_weekday',
        label: 'Dia da semana do pagamento',
        type: 'select',
        options: [
          { label: 'Segunda-feira', value: 'monday' },
          { label: 'Terça-feira', value: 'tuesday' },
          { label: 'Quarta-feira', value: 'wednesday' },
          { label: 'Quinta-feira', value: 'thursday' },
          { label: 'Sexta-feira', value: 'friday' },
        ],
      },
      { key: 'driver_score', label: 'Score do motorista', type: 'number' },
      { key: 'notes', label: 'Observações', type: 'textarea' },
    ],
    listColumns: ['name', 'cpf', 'phone', 'payment_weekday', 'cnh_due_date', 'driver_score'],
  },

  multas: {
    slug: 'multas',
    title: 'Multas',
    table: 'fines',
    orderBy: { column: 'created_at', ascending: false },
    fields: [
      {
        key: 'vehicle_id',
        label: 'Veículo',
        type: 'select',
        relation: {
          table: 'vehicles',
          valueKey: 'id',
          labelKey: 'plate',
          secondaryLabelKey: 'model',
          orderBy: { column: 'plate', ascending: true },
        },
      },
      {
        key: 'driver_id',
        label: 'Motorista',
        type: 'select',
        relation: {
          table: 'drivers',
          valueKey: 'id',
          labelKey: 'name',
          secondaryLabelKey: 'phone',
          orderBy: { column: 'name', ascending: true },
        },
      },
      { key: 'date', label: 'Data', type: 'date', required: true },
      { key: 'due_date', label: 'Data de vencimento', type: 'date' },
      { key: 'amount', label: 'Valor', type: 'number' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Pendente', value: 'pending' },
          { label: 'Pago', value: 'paid' },
          { label: 'Recorrido', value: 'appealed' },
        ],
      },
      { key: 'description', label: 'Descrição', type: 'textarea' },
    ],
    listColumns: ['date', 'vehicle_id', 'driver_id', 'amount', 'due_date', 'status'],
  },

  vistorias: {
    slug: 'vistorias',
    title: 'Vistorias',
    table: 'inspections',
    orderBy: { column: 'created_at', ascending: false },
    fields: [
      {
        key: 'vehicle_id',
        label: 'Veículo',
        type: 'select',
        relation: {
          table: 'vehicles',
          valueKey: 'id',
          labelKey: 'plate',
          secondaryLabelKey: 'model',
          orderBy: { column: 'plate', ascending: true },
        },
      },
      {
        key: 'driver_id',
        label: 'Motorista',
        type: 'select',
        relation: {
          table: 'drivers',
          valueKey: 'id',
          labelKey: 'name',
          orderBy: { column: 'name', ascending: true },
        },
      },
      { key: 'date', label: 'Data', type: 'date', required: true },
      { key: 'completed', label: 'Concluída', type: 'checkbox' },
      { key: 'notes', label: 'Observações', type: 'textarea' },
    ],
    listColumns: ['date', 'vehicle_id', 'driver_id', 'completed', 'notes'],
  },

  socios: {
    slug: 'socios',
    title: 'Sócios',
    table: 'investors',
    orderBy: { column: 'created_at', ascending: false },
    fields: [
      { key: 'name', label: 'Nome do sócio', type: 'text', required: true },
      { key: 'phone', label: 'Telefone', type: 'text' },
      { key: 'cpf', label: 'CPF/CNPJ', type: 'text' },
      { key: 'active_cars', label: 'Carros ativos', type: 'number' },
      {
        key: 'partnership_type',
        label: 'Tipo de parceria',
        type: 'select',
        options: [
          { label: 'Carros ativos', value: 'carros_ativos' },
          { label: 'Investidor', value: 'investidor' },
          { label: 'Administração', value: 'administracao' },
        ],
      },
      { key: 'notes', label: 'Observações', type: 'textarea' },
    ],
    listColumns: ['name', 'phone', 'cpf', 'active_cars', 'partnership_type'],
  },

  financeiro: {
    slug: 'financeiro',
    title: 'Financeiro',
    table: 'financial_entries',
    orderBy: { column: 'date', ascending: false },
    fields: [
      { key: 'date', label: 'Data', type: 'date', required: true },
      { key: 'rent_value', label: 'Valor do aluguel', type: 'number' },
     { key: 'adm_fee', label: '% Repasse ADM/Motorista', type: 'number' },
{ key: 'repasse_value', label: '% Repasse do sócio', type: 'number' },
      { key: 'expense_value', label: 'Valor da despesa', type: 'number' },
      { key: 'description', label: 'Descrição da despesa', type: 'textarea' },
      {
        key: 'vehicle_id',
        label: 'Veículo',
        type: 'select',
        relation: {
          table: 'vehicles',
          valueKey: 'id',
          labelKey: 'plate',
          secondaryLabelKey: 'model',
          orderBy: { column: 'plate', ascending: true },
        },
      },
      {
        key: 'driver_id',
        label: 'Motorista',
        type: 'select',
        relation: {
          table: 'drivers',
          valueKey: 'id',
          labelKey: 'name',
          orderBy: { column: 'name', ascending: true },
        },
      },
      { key: 'nf_photo', label: 'Foto da NF (JPG)', type: 'file' },
    ],
    listColumns: [
      'date',
      'rent_value',
      'adm_fee',
      'repasse_value',
      'expense_value',
      'vehicle_id',
      'driver_id',
    ],
  },

  contratos: {
    slug: 'contratos',
    title: 'Contratos',
    table: 'contracts',
    orderBy: { column: 'created_at', ascending: false },
    fields: [
      {
        key: 'driver_id',
        label: 'Motorista',
        type: 'select',
        relation: {
          table: 'drivers',
          valueKey: 'id',
          labelKey: 'name',
          secondaryLabelKey: 'phone',
          orderBy: { column: 'name', ascending: true },
        },
      },
      {
        key: 'investor_id',
        label: 'Sócio',
        type: 'select',
        relation: {
          table: 'investors',
          valueKey: 'id',
          labelKey: 'name',
          orderBy: { column: 'name', ascending: true },
        },
      },
      {
        key: 'vehicle_id',
        label: 'Veículo',
        type: 'select',
        relation: {
          table: 'vehicles',
          valueKey: 'id',
          labelKey: 'plate',
          secondaryLabelKey: 'model',
          orderBy: { column: 'plate', ascending: true },
        },
      },
      {
        key: 'contract_kind',
        label: 'Tipo de contrato',
        type: 'select',
        options: [
          { label: 'Aluguel', value: 'aluguel' },
          { label: 'Venda em forma de aluguel', value: 'venda_aluguel' },
        ],
      },
      { key: 'start_date', label: 'Data de início', type: 'date', required: true },
      { key: 'end_date', label: 'Data de fim', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: statusOptions },
      { key: 'rent_value', label: 'Valor do aluguel', type: 'number' },
      { key: 'repasse_value', label: 'Valor de repasse', type: 'number' },
      {
        key: 'payment_weekday',
        label: 'Dia da semana do pagamento do aluguel',
        type: 'select',
        options: [
          { label: 'Segunda-feira', value: 'monday' },
          { label: 'Terça-feira', value: 'tuesday' },
          { label: 'Quarta-feira', value: 'wednesday' },
          { label: 'Quinta-feira', value: 'thursday' },
          { label: 'Sexta-feira', value: 'friday' },
        ],
      },
      { key: 'monthly_payment_day', label: 'Dia mensal do pagamento de venda', type: 'number' },
      { key: 'allowed_delay_days', label: 'Dias de atraso permitido', type: 'number' },
      { key: 'late_fee', label: 'Multa por atraso', type: 'number' },
      { key: 'contract_file_url', label: 'Link do contrato assinado/PDF', type: 'text' },
      { key: 'photos_url', label: 'Link das fotos/documentos', type: 'text' },
      { key: 'notes', label: 'Observações', type: 'textarea' },
    ],
    listColumns: [
      'driver_id',
      'vehicle_id',
      'contract_kind',
      'start_date',
      'end_date',
      'status',
      'rent_value',
      'repasse_value',
    ],
  },
} satisfies Record<string, CrudModuleConfig>;

export type ModuleSlug = keyof typeof moduleConfigs;