import type { CrudModuleConfig } from '@/lib/types';


export const menuItems = [
  { label: 'Painel Administrativo', href: '/dashboard' },
  { label: 'Painel Financeiro', href: '/financeiro' },
  { label: 'Alertas', href: '/alertas' },
  { label: 'Veículos', href: '/veiculos' },
  { label: 'Motoristas', href: '/motoristas' },
  { label: 'Sócios', href: '/socios' },
  { label: 'Contratos', href: '/contratos' },
 { label: 'Vistorias', href: '/vistorias' },
{ label: 'Multas', href: '/multas' },
{ label: 'Pagamentos', href: '/pagamentos' },
  { label: 'Rastreamento', href: '/rastreamento' },
  { label: 'IAdrive', href: '/copiloto' },
];

const statusOptions = [
  { label: 'Ativo', value: 'active' },
  { label: 'Inativo', value: 'inactive' },
];

export const moduleConfigs = {

  veiculos: {
    slug: 'veiculos',
    title: 'Veículos',
    table: 'vehicles',
    orderBy: { column: 'created_at', ascending: false },
    fields: [
      { key: 'plate', label: 'Placa', type: 'text', required: true },
      { key: 'brand', label: 'Marca', type: 'text' },
      { key: 'model', label: 'Modelo', type: 'text' },
      { key: 'year', label: 'Ano', type: 'number' },
      {
        key: 'driver_id',
        label: 'Motorista vinculado',
        type: 'select',
        relation: {
          table: 'drivers',
          valueKey: 'id',
          labelKey: 'name',
          secondaryLabelKey: 'phone',
          orderBy: { column: 'name', ascending: true },
        },
      },
      { key: 'chassis', label: 'Chassi', type: 'text' },
      { key: 'renavan', label: 'Renavam', type: 'text' },
      { key: 'color', label: 'Cor do carro', type: 'text' },
      { key: 'km_initial', label: 'KM inicial', type: 'number' },
      { key: 'km_per_month', label: 'KM mensal', type: 'number' },
      { key: 'last_maintenance', label: 'Data da última vistoria', type: 'date' },
      { key: 'next_revision', label: 'Data da próxima vistoria', type: 'date' },
      { key: 'vehicle_photo_url', label: 'Foto ou PDF do documento do carro', type: 'file' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Disponível', value: 'available' },
          { label: 'Alugado', value: 'rented' },
          { label: 'Vendido em forma de aluguel', value: 'sold' },
          { label: 'Manutenção', value: 'maintenance' },
        ],
      },
      {
        key: 'financing_status',
        label: 'Quitado ou financiado',
        type: 'select',
        options: [
          { label: 'Quitado', value: 'quitado' },
          { label: 'Financiado', value: 'financiado' },
        ],
      },
      { key: 'installments_total', label: 'Quantidade de parcelas', type: 'number' },
      { key: 'installment_value', label: 'Valor da parcela', type: 'number' },
      { key: 'financing_end_date', label: 'Data final do financiamento', type: 'date' },
      { key: 'notes', label: 'Observações', type: 'textarea' },
    ],
    listColumns: [
      'plate', 'brand', 'model', 'year', 'driver_id', 'color',
      'km_initial', 'km_per_month', 'last_maintenance', 'next_revision',
      'status', 'financing_status',
    ],
  },

  motoristas: {
    slug: 'motoristas',
    title: 'Motoristas',
    table: 'drivers',
    orderBy: { column: 'created_at', ascending: false },
    fields: [
      { key: 'name', label: 'Nome', type: 'text', required: true },
      { key: 'cpf', label: 'CPF', type: 'text' },
      { key: 'phone', label: 'Telefone', type: 'text' },
      { key: 'cep', label: 'CEP', type: 'text' },
      { key: 'address', label: 'Endereço', type: 'text' },
      { key: 'latitude', label: 'Latitude', type: 'number' },
      { key: 'longitude', label: 'Longitude', type: 'number' },
      { key: 'cnh_due_date', label: 'Vencimento da CNH', type: 'date' },
      {
        key: 'payment_weekday',
        label: 'Dia da semana do pagamento',
        type: 'select',
        options: [
          { label: 'Segunda-feira', value: 'monday' },
          { label: 'Terça-feira', value: 'tuesday' },
          { label: 'Quarta-feira', value: 'wednesday' },
          { label: 'Quinta-feira', value: 'thursday' },
          { label: 'Sexta-feira', value: 'friday' },
        ],
      },
      {
        key: 'rental_mode',
        label: 'Tipo de contrato do motorista',
        type: 'select',
        options: [
          { label: 'Aluguel', value: 'aluguel' },
          { label: 'Venda em forma de aluguel', value: 'venda_aluguel' },
        ],
      },
      { key: 'rent_amount', label: 'Valor da parcela que deve pagar', type: 'number' },
      {
        key: 'vehicle_id',
        label: 'Veículo alugado/comprado',
        type: 'select',
        relation: {
          table: 'vehicles',
          valueKey: 'id',
          labelKey: 'plate',
          secondaryLabelKey: 'model',
          orderBy: { column: 'plate', ascending: true },
        },
      },
      { key: 'insurance_primary_driver', label: 'Principal condutor no seguro', type: 'checkbox' },
      { key: 'driver_score', label: 'Score do motorista', type: 'number' },
      { key: 'reference1_name', label: 'Referência 1 - Nome', type: 'text' },
      { key: 'reference1_phone', label: 'Referência 1 - Telefone', type: 'text' },
      { key: 'reference2_name', label: 'Referência 2 - Nome', type: 'text' },
      { key: 'reference2_phone', label: 'Referência 2 - Telefone', type: 'text' },
      { key: 'social_media_link', label: 'Link da rede social', type: 'text' },
      { key: 'cnh_file_url', label: 'CNH do motorista (foto ou PDF)', type: 'file' },
      { key: 'app_photo_path', label: 'Foto do app (JPG)', type: 'file' },
      { key: 'residence_photo_path', label: 'Comprovante de residência (JPG)', type: 'file' },
      { key: 'residence_front_photo_path', label: 'Foto da frente da residência (JPG)', type: 'file' },
      { key: 'signed_contract_pdf_path', label: 'Contrato assinado (PDF)', type: 'file' },
      { key: 'criminal_record_photo_path', label: 'Antecedentes criminais (PDF)', type: 'file' },
      { key: 'notes', label: 'Observações', type: 'textarea' },
    ],
    listColumns: [
      'name', 'cpf', 'phone', 'vehicle_id', 'rental_mode',
      'rent_amount', 'payment_weekday', 'cnh_due_date', 'driver_score',
    ],
  },

  vistorias: {
    slug: 'vistorias',
    title: 'Vistorias',
    table: 'inspections',
    orderBy: { column: 'date', ascending: false },
    fields: [
      {
        key: 'vehicle_id',
        label: 'Veículo',
        type: 'select',
        required: true,
        relation: {
          table: 'vehicles',
          valueKey: 'id',
          labelKey: 'plate',
          secondaryLabelKey: 'model',
          orderBy: { column: 'plate', ascending: true },
        },
      },
      {
        key: 'driver_id',
        label: 'Motorista',
        type: 'select',
        relation: {
          table: 'drivers',
          valueKey: 'id',
          labelKey: 'name',
          orderBy: { column: 'name', ascending: true },
        },
      },
     { key: 'date', label: 'Data da vistoria', type: 'date', required: true },
{ key: 'km', label: 'KM atual', type: 'number' },
{ key: 'valor_gasto', label: 'Valor gasto', type: 'number' },
{ key: 'observations', label: 'Serviços realizados / Observações', type: 'textarea' },
{ key: 'next_revision_date', label: 'Data da próxima revisão', type: 'date' },
      {
        key: 'concluida',
        label: 'Status da vistoria',
        type: 'select',
        options: [
          { label: 'Pendente', value: 'Pendente' },
          { label: 'Concluída', value: 'Concluída' },
        ],
      },
    ],
listColumns: [
  'date',
  'vehicle_id',
  'driver_id',
  'km',
  'valor_gasto',
  'observations',
  'next_revision_date',
  'concluida',
],
  },

  multas: {
    slug: 'multas',
    title: 'Multas',
    table: 'fines',
    orderBy: { column: 'created_at', ascending: false },
    fields: [
      {
        key: 'driver_id',
        label: 'Motorista',
        type: 'select',
        relation: {
          table: 'drivers',
          valueKey: 'id',
          labelKey: 'name',
          secondaryLabelKey: 'phone',
          orderBy: { column: 'name', ascending: true },
        },
      },
      {
        key: 'vehicle_id',
        label: 'Veículo',
        type: 'select',
        relation: {
          table: 'vehicles',
          valueKey: 'id',
          labelKey: 'plate',
          secondaryLabelKey: 'model',
          orderBy: { column: 'plate', ascending: true },
        },
      },
      { key: 'due_date', label: 'Data de vencimento', type: 'date', required: true },
      { key: 'amount', label: 'Valor da multa', type: 'number', required: true },
      {
        key: 'status',
        label: 'Status da multa',
        type: 'select',
        options: [
          { label: 'Pendente', value: 'pendente' },
          { label: 'Paga', value: 'paga' },
          { label: 'Vencida', value: 'vencida' },
        ],
      },
      { key: 'description', label: 'Observações', type: 'textarea' },
    ],
    listColumns: ['driver_id', 'vehicle_id', 'due_date', 'amount', 'status'],
  },

  pagamentos: {
  slug: 'pagamentos',
  title: 'Pagamentos e Recuperações',
  table: 'payment_records',
  orderBy: { column: 'due_date', ascending: false },
  fields: [
    {
      key: 'driver_id',
      label: 'Motorista',
      type: 'select',
      relation: {
        table: 'drivers',
        valueKey: 'id',
        labelKey: 'name',
        secondaryLabelKey: 'phone',
        orderBy: { column: 'name', ascending: true },
      },
    },
    {
      key: 'vehicle_id',
      label: 'Veículo',
      type: 'select',
      relation: {
        table: 'vehicles',
        valueKey: 'id',
        labelKey: 'plate',
        secondaryLabelKey: 'model',
        orderBy: { column: 'plate', ascending: true },
      },
    },
    {
      key: 'investor_id',
      label: 'Sócio',
      type: 'select',
      relation: {
        table: 'investors',
        valueKey: 'id',
        labelKey: 'name',
        orderBy: { column: 'name', ascending: true },
      },
    },
    {
      key: 'charge_type',
      label: 'Tipo de cobrança',
      type: 'select',
      options: [
        { label: 'Aluguel', value: 'aluguel' },
        { label: 'Seguro', value: 'seguro' },
        { label: 'Rastreador', value: 'rastreador' },
        { label: 'Multa por atraso', value: 'multa_atraso' },
        { label: 'Guincho', value: 'guincho' },
        { label: 'Recuperação de veículo', value: 'recuperacao_veiculo' },
        { label: 'Outros', value: 'outros' },
      ],
    },
    {
      key: 'payment_frequency',
      label: 'Frequência do pagamento',
      type: 'select',
      options: [
        { label: 'Semanal', value: 'semanal' },
        { label: 'Mensal', value: 'mensal' },
      ],
    },
    { key: 'due_date', label: 'Data prevista de pagamento', type: 'date', required: true },
    { key: 'paid_date', label: 'Data em que pagou', type: 'date' },
    { key: 'rent_value', label: 'Valor do aluguel', type: 'number' },
    { key: 'insurance_value', label: 'Valor do seguro', type: 'number' },
    { key: 'tracker_value', label: 'Valor do rastreador', type: 'number' },
    { key: 'late_fee_value', label: 'Multa por atraso', type: 'number' },
    { key: 'amount_paid', label: 'Valor pago', type: 'number' },
    { key: 'allowed_delay_days', label: 'Dias de atraso permitido', type: 'number' },
    {
      
  key: 'payment_status',
  label: 'Status do pagamento',
  type: 'select',
  options: [
    { label: 'Pendente', value: 'pendente' },
    { label: 'Pago no prazo', value: 'pago_no_prazo' },
    { label: 'Pago com atraso', value: 'pago_com_atraso' },
    { label: 'Atrasado', value: 'atrasado' },
    { label: 'Em cobrança', value: 'em_cobranca' },
    { label: 'Recuperação acionada', value: 'recuperacao_acionada' },
    { label: 'Veículo recuperado', value: 'veiculo_recuperado' },
    { label: 'Cancelado', value: 'cancelado' },
  ],
},

{ key: 'vehicle_recovery_needed', label: 'Precisou recuperar o veículo?', type: 'checkbox' },
{ key: 'recovery_date', label: 'Data da recuperação', type: 'date', required: false },
{ key: 'recovery_reason', label: 'Motivo da recuperação', type: 'textarea', required: false },
    {
      key: 'recovery_status',
      label: 'Status da recuperação',
      type: 'select',
      options: [
        { label: 'Não acionada', value: 'nao_acionada' },
        { label: 'Acionada', value: 'acionada' },
        { label: 'Em andamento', value: 'em_andamento' },
        { label: 'Veículo recuperado', value: 'veiculo_recuperado' },
        { label: 'Cancelada', value: 'cancelada' },
      ],
    },
    { key: 'tow_value', label: 'Valor total do guincho', type: 'number' },
    { key: 'tow_driver_value', label: 'Parte do motorista no guincho', type: 'number', readonly: true },
    { key: 'tow_admin_value', label: 'Parte da ADM no guincho', type: 'number', readonly: true },
    { key: 'tow_investor_value', label: 'Parte do sócio no guincho', type: 'number', readonly: true },
    { key: 'observations', label: 'Observações', type: 'textarea' },
    { key: 'payment_receipt_url', label: 'Comprovante de pagamento', type: 'file' },
  ],
  listColumns: [
    'due_date',
    'driver_id',
    'vehicle_id',
    'investor_id',
    'payment_frequency',
    'rent_value',
    'insurance_value',
    'tracker_value',
    'total_charged',
    'amount_paid',
    'delay_days',
    'payment_status',
    'vehicle_recovery_needed',
    'tow_value',
  ],
},

  socios: {
    slug: 'socios',
    title: 'Sócios',
    table: 'investors',
    orderBy: { column: 'created_at', ascending: false },
    fields: [
      { key: 'name', label: 'Nome do sócio', type: 'text', required: true },
      { key: 'phone', label: 'Telefone', type: 'text' },
      { key: 'cpf', label: 'CPF/CNPJ', type: 'text' },
      {
        key: 'active_cars',
        label: 'Carros ativos',
        type: 'multiselect',
        relation: {
          table: 'vehicles',
          valueKey: 'id',
          labelKey: 'plate',
          secondaryLabelKey: 'model',
          orderBy: { column: 'plate', ascending: true },
        },
      },
      { key: 'adm_percentage', label: '% Administração', type: 'number' },
      { key: 'partner_percentage', label: '% Sócio', type: 'number' },
      { key: 'notes', label: 'Observações', type: 'textarea' },
    ],
    listColumns: ['name', 'phone', 'cpf', 'active_cars', 'adm_percentage', 'partner_percentage'],
  },

  financeiro: {
    slug: 'financeiro',
    title: 'Financeiro',
    table: 'financial_entries',
    orderBy: { column: 'date', ascending: false },
    fields: [
      { key: 'date', label: 'Data', type: 'date', required: true },
      {
        key: 'vehicle_id',
        label: 'Veículo',
        type: 'select',
        relation: {
          table: 'vehicles',
          valueKey: 'id',
          labelKey: 'plate',
          secondaryLabelKey: 'model',
          orderBy: { column: 'plate', ascending: true },
        },
      },
      {
        key: 'driver_id',
        label: 'Motorista',
        type: 'select',
        relation: {
          table: 'drivers',
          valueKey: 'id',
          labelKey: 'name',
          orderBy: { column: 'name', ascending: true },
        },
      },
      { key: 'rent_value', label: 'Valor do aluguel recebido', type: 'number' },
      { key: 'adm_fee', label: '% Repasse ADM/Motorista', type: 'number' },
      { key: 'repasse_value', label: '% Repasse do sócio', type: 'number' },
      { key: 'expense_value', label: 'Valor da despesa', type: 'number' },
      {
        key: 'expense_type',
        label: 'Tipo de despesa',
        type: 'select',
        options: [
          { label: 'Combustível', value: 'combustivel' },
          { label: 'Manutenção / Vistoria', value: 'manutencao' },
          { label: 'Seguro', value: 'seguro' },
          { label: 'IPVA / Licenciamento', value: 'ipva' },
          { label: 'Rastreador', value: 'rastreador' },
          { label: 'Multa', value: 'multa' },
          { label: 'Financiamento / Parcela', value: 'financiamento' },
          { label: 'Outros', value: 'outros' },
        ],
      },
      { key: 'description', label: 'Descrição / Observações', type: 'textarea' },
      { key: 'nf_photo', label: 'Foto da NF (JPG)', type: 'file' },
    ],
    listColumns: [
      'date', 'vehicle_id', 'driver_id', 'expense_type',
      'expense_value', 'rent_value', 'adm_fee', 'repasse_value',
    ],
  },

  contratos: {
    slug: 'contratos',
    title: 'Contratos',
    table: 'contracts',
    orderBy: { column: 'created_at', ascending: false },
    fields: [
      {
        key: 'driver_id',
        label: 'Motorista',
        type: 'select',
        relation: {
          table: 'drivers',
          valueKey: 'id',
          labelKey: 'name',
          secondaryLabelKey: 'phone',
          orderBy: { column: 'name', ascending: true },
        },
      },
      {
        key: 'investor_id',
        label: 'Sócio',
        type: 'select',
        relation: {
          table: 'investors',
          valueKey: 'id',
          labelKey: 'name',
          orderBy: { column: 'name', ascending: true },
        },
      },
      {
        key: 'vehicle_id',
        label: 'Veículo',
        type: 'select',
        relation: {
          table: 'vehicles',
          valueKey: 'id',
          labelKey: 'plate',
          secondaryLabelKey: 'model',
          orderBy: { column: 'plate', ascending: true },
        },
      },
      {
        key: 'contract_kind',
        label: 'Tipo de contrato',
        type: 'select',
        options: [
          { label: 'Aluguel', value: 'aluguel' },
          { label: 'Venda em forma de aluguel', value: 'venda_aluguel' },
        ],
      },
      { key: 'start_date', label: 'Data de início', type: 'date', required: true },
      { key: 'end_date', label: 'Data de fim', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: statusOptions },
      { key: 'rent_value', label: 'Valor do aluguel', type: 'number' },
      { key: 'repasse_value', label: 'Repasse sócio', type: 'number' },
      { key: 'adm_repasse_value', label: 'Repasse ADM', type: 'number' },
      {
        key: 'payment_weekday',
        label: 'Dia da semana do pagamento do aluguel',
        type: 'select',
        options: [
          { label: 'Segunda-feira', value: 'monday' },
          { label: 'Terça-feira', value: 'tuesday' },
          { label: 'Quarta-feira', value: 'wednesday' },
          { label: 'Quinta-feira', value: 'thursday' },
          { label: 'Sexta-feira', value: 'friday' },
        ],
      },
      { key: 'monthly_payment_day', label: 'Dia mensal do pagamento de venda', type: 'number' },
      { key: 'allowed_delay_days', label: 'Dias de atraso permitido', type: 'number' },
      { key: 'late_fee', label: 'Multa por atraso', type: 'number' },
      { key: 'contract_pdf_path', label: 'Contrato assinado (PDF)', type: 'file' },
      { key: 'notes', label: 'Observações', type: 'textarea' },
    ],
    listColumns: [
      'driver_id', 'vehicle_id', 'contract_kind', 'start_date',
      'end_date', 'status', 'rent_value', 'repasse_value',
    ],
  },

} satisfies Record<string, CrudModuleConfig>;

export type ModuleSlug = keyof typeof moduleConfigs;